M48
; DRILL file {KiCad 9.0.6} date 2025-12-11T14:54:14+0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-11T14:54:14+06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X99.608Y-89.662
X99.608Y-114.172
X146.558Y-89.662
X146.558Y-114.172
M30
